/*
 * Copyright (c) 2026 Adam G. Sweeney <agsweeney@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "TrigLUT.h"
#include <math.h>

namespace ClearCore {

// Lookup table for sine values (Q15 format)
// Table contains 1024 entries covering 0 to 2π
// Each entry represents sin(angle) * 32768
// This file is generated by a Python script
#include "TrigLUT_Data.h"

/**
    \brief Get sine value from lookup table with linear interpolation
    
    Uses lookup table with linear interpolation for smooth results.
**/
int32_t SinQx(int32_t angleQx) {
    // Normalize angle to 0-32768 range (0-2π)
    angleQx &= 0x7FFF; // Mask to 15 bits (0-32767)
    
    // Convert Q15 angle to table index (0-1023)
    // angleQx ranges 0-32767, we want 0-1023
    // index = (angleQx * 1024) / 32768 = angleQx / 32
    uint32_t index = (angleQx >> 5) & 0x3FF; // Divide by 32, mask to 10 bits
    
    // Get fractional part for interpolation (0-31)
    uint32_t frac = angleQx & 0x1F;
    
    // Get two table entries for interpolation
    int32_t val1 = sinLUT[index];
    int32_t val2 = sinLUT[(index + 1) & 0x3FF];
    
    // Linear interpolation: val1 + (val2 - val1) * frac / 32
    int32_t diff = val2 - val1;
    return val1 + ((diff * (int32_t)frac) >> 5);
}

/**
    \brief Get cosine value (sine shifted by π/2)
    
    cos(θ) = sin(θ + π/2) = sin(θ + 8192) in Q15
**/
int32_t CosQx(int32_t angleQx) {
    // cos(θ) = sin(θ + π/2)
    // π/2 in Q15 = 8192
    return SinQx(angleQx + 8192);
}

} // ClearCore namespace
