"""ClearAI host: JSON-RPC Lines client for Code as Policies gantry primitives."""

from .client import ClearAiClient, discover
from .primitives import (
    clear_alerts,
    configure,
    connect_serial,
    connect_tcp,
    disable,
    dwell,
    enable,
    estop,
    get_capabilities,
    get_pose,
    get_status,
    jog,
    move_arc,
    move_linear,
    read_inputs,
    set_mode,
    set_test_mode,
    set_units,
    set_units_a,
    set_work_origin,
    stop,
    wait_idle,
    write_output,
    queue_status,
    queue_clear,
    home,
    probe,
    keepalive,
    configure_safety,
)

__all__ = [
    "ClearAiClient",
    "clear_alerts",
    "configure",
    "connect_serial",
    "connect_tcp",
    "discover",
    "disable",
    "dwell",
    "enable",
    "estop",
    "get_capabilities",
    "get_pose",
    "get_status",
    "jog",
    "move_arc",
    "move_linear",
    "read_inputs",
    "set_mode",
    "set_test_mode",
    "set_units",
    "set_units_a",
    "set_work_origin",
    "stop",
    "wait_idle",
    "write_output",
    "queue_status",
    "queue_clear",
    "home",
    "probe",
    "keepalive",
    "configure_safety",
]
